### ISSUE TITLE
Problem when release archive xcode 'manage_calendar_events/ManageCalendarEventsPlugin.h' file not found

### ISSUE THREAD

**Issue by nagamuralik** [lakshmanaprabhu/manage_calendar_events#1]
'manage_calendar_events/ManageCalendarEventsPlugin.h' file not found

**Comment by lakshmanaprabhu** [comment]
Hi @nagamuralik, Thanks for using this plugin. 
I have updated the plugin with the latest SDK support. Hopefully, you may not face this issue again. 
Kindly verify.
