### ISSUE TITLE
App Crash on integrating with Calendar using manage_calendar_events Plugin

### ISSUE THREAD

**Issue by Akshayc22** [lakshmanaprabhu/manage_calendar_events#2]
While i am trying to add reminder in iOS mobile calendar using simulator app gets crash, i need to check in real device if it is crashing in real device also.

**Comment by lakshmanaprabhu** [comment]
Hi @Akshayc22, Kindly share some logs to track the issue.

**Comment by cis-emp1822** [comment]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/cis/.pub-cache/hosted/pub.dartlang.org/manage_calendar_events-1.0.3/ios/Classes/SwiftManageCalendarEventsPlugin.swift, line 221
Lost connection to device.
Hello @lakshmanaprabhu this is the error just before crash
