### ISSUE TITLE
Issue _myPlugin.createEvent( )  📆 

### ISSUE THREAD

**Issue by chryshel** [lakshmanaprabhu/manage_calendar_events#25]
### Issue 

 I am trying to add an event/events to calendars, but  in Android platform it always throws an error when running the  _myPlugin.createEvent() method.

 ### Code snippet           
for(int i =0; i < calendarIdList.length; i++) {   /// list of calendar ids
 for(int a = 0; a < activities.length; a++) {  /// list of events 
     CalendarEvent _newEvent = CalendarEvent(
            title: activities[a].title,
            description: activities[a].description == null ? "this activity does not include a description" : activities[a].description,
            startDate: DateTime.parse(activities[a].startDt!),
            endDate: DateTime.parse(activities[a].endDt!),
          );
     _myPlugin.createEvent(calendarId: calendarIdList[i], event: _newEvent);
  }
}

### Further  info

* Even I get this error, app won't crash and event is also adding to the calendar successfully.
* Tried to run _myPlugin.createEvent() without any loops, but it also doesn't work .

### Output 

E/MethodChannel#manage_calendar_events(27822): Failed to handle method call
E/MethodChannel#manage_calendar_events(27822): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/MethodChannel#manage_calendar_events(27822): 	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.addAttendees(ManageCalendarEventsPlugin.java:177)
E/MethodChannel#manage_calendar_events(27822): 	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.onMethodCall(ManageCalendarEventsPlugin.java:133)
E/MethodChannel#manage_calendar_events(27822): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#manage_calendar_events(27822): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#manage_calendar_events(27822): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#manage_calendar_events(27822): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#manage_calendar_events(27822): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#manage_calendar_events(27822): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#manage_calendar_events(27822): 	at android.app.ActivityThread.main(ActivityThread.java:8587)
E/MethodChannel#manage_calendar_events(27822): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#manage_calendar_events(27822): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#manage_calendar_events(27822): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/flutter (27822): PlatformException(error, Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
I/flutter (27822): 	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.addAttendees(ManageCalendarEventsPlugin.java:177)
I/flutter (27822): 	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.onMethodCall(ManageCalendarEventsPlugin.java:133)
I/flutter (27822): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (27822): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
I/flutter (27822): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
I/flutter (27822): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (27822): 	at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter (27822): 	at android.os.Looper.loop(Looper.java:206)
I/flutter (27822): 	at android.app.ActivityThread.main(ActivityThread.java:8587)

**Comment by ignacio008** [comment]
Disculpa lo pudiste resolver??? tengo el mismo problema

**Comment by lakshmanaprabhu** [comment]
Try with the given example whether is it working or not. Feel free to comment, even the example also not working for you
