### ISSUE TITLE
On IOS App crashing when creating Events

### ISSUE THREAD

**Issue by cresusjpt** [lakshmanaprabhu/manage_calendar_events#3]
I have this error when running on iOS. I didn't observe same error in android platform : Could not cast value of type 'NSNull' (0x7fff86cd6d08) to 'NSString' (0x7fff86cfbd00).

The code is crashing on createEvent method, suppose it's eventId attributes

```
try{
        String eventId = await _myPlugin.createEvent(calendarId: calendarDefault.id, event: _newEvent);
        setState(() {
          minuteur.eventId = eventId;
          _addReminder(minuteur.eventId, 1);
          Provider.of<MinuteurDao>(context).updateMinuteur(minuteur);
          _saving = false;
          print("Event Id is: $eventId");
        });
}catch (exception){
     print(exception);
 }
```

**Comment by lakshmanaprabhu** [comment]
Thank you @cresusjpt to let me know this. 
I have revised the code to fix the issue which you have mentioned. 

Reason:
> iOS code in my plugin was expecting a non-null location value and hopefully, you have not passed location while creating an event (_newEvent). This way I can reproduce this issue and fixed the same.

**Comment by cresusjpt** [comment]
I think it's not only location null because i passed to it a default value but getting the same error.  Perhaps i'm wrong. I will rebuild the project this night and feedback you.

**Comment by cresusjpt** [comment]
@lakshmanaprabhu I just try it and getting the same issue.
