### ISSUE TITLE
createEvent does not take the location string

### ISSUE THREAD

**Issue by julian247** [lakshmanaprabhu/manage_calendar_events#4]
Hi there,

this plugin is great. Thank you for your work. I have only one issue at the moment. When I create a new event (see your code below), then I have the problem that the location string does not show up in the device calendar. Despite of the location, the rest works. Do you have a guess where the problem is?

Thanks in advance!

`void _addEvent() async {
    DateTime startDate = DateTime.now();
    DateTime endDate = startDate.add(Duration(hours: 3));
    CalendarEvent _newEvent = CalendarEvent(
        title: "Event from plugin",
        description: "test plugin description",
    startDate: startDate,
    endDate: endDate,
    location: "Chennai, Tamilnadu");
    _myPlugin
        .createEvent(calendarId: widget.calendarId, event: _newEvent)
        .then((evenId) {
    setState(() {
    print("Event Id is: $evenId");
    });
    });
  }`

**Comment by lakshmanaprabhu** [comment]
@julian247 Hopefully, the recent versions have fixed the issue. Kindly verify with your code. 
If you face a similar issue again, kindly let me know. 
Thanks.
