### ISSUE TITLE
Build error - " does not specify a Swift version ..."

### ISSUE THREAD

**Issue by bremington** [lakshmanaprabhu/manage_calendar_events#5]
Hi,

I am getting this error when building my code with your package

`manage_calendar_events` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by lakshmanaprabhu** [comment]
Hi @bremington, 
To fix the mentioned issue, kindly go through the following links

- https://github.com/esysberlin/esys-flutter-share/issues/24#issuecomment-527611976
- https://stackoverflow.com/questions/54912188/flutter-ios-build-fail-on-running-pod-install
- https://github.com/ko2ic/image_downloader/issues/9

One of the discussions will solve the mentioned issue on your side.
