### ISSUE TITLE
[isAllDay] parameter not used when [createUpdateEvent]

### ISSUE THREAD

**Issue by sageata** [lakshmanaprabhu/manage_calendar_events#7]
First of all, thank you for this package.

I found the following bug while using the package.

The ```isAllDay``` parameter is not  used when updating or creating an event

All it needs to be done is to add the following lines in ```SwiftManageCalendarEventsPlugin.swift```

```let isAllDay = event.isAllDay``` at line 206
and
```ekEvent!.isAllDay = isAllDay``` at line 228

<img width="616" alt="Screen Shot 2021-04-17 at 5 08 52 PM" src="https://user-images.githubusercontent.com/26434396/115114498-d14cff00-9fa0-11eb-8086-81892b3a3c02.png">

I could do a pull request, but considering how little needs to be done I think is easier to just modify it in the master repo.

I didn't check the Android thing to see if it needs fixing or not.

Thank you!

**Comment by lakshmanaprabhu** [comment]
First of all Thanks @sageata. Added this change in the master repo.
