### ISSUE TITLE
getEvents returns all events from the last 3 years

### ISSUE THREAD

**Issue by adailydose** [lakshmanaprabhu/manage_calendar_events#8]
I noticed that getEvents will return all the events on my calendar for the last 3 years. This results in a TON of events, and I think there is some truncation or memory limit, because many events just don't show up. Is there a way to just view the events for the day, or the week, or even just this month using this library?

This was tested on an Android device.

**Comment by lakshmanaprabhu** [comment]
Thanks @adailydose for the suggestion. 
Added getEventsByDateRange() method to fetch the events between two dates.
