### ISSUE TITLE
Event url

### ISSUE THREAD

**Issue by EmanueleVolpato** [lakshmanaprabhu/manage_calendar_events#9]
Is possible to implement url for an event? Tnk

**Comment by lakshmanaprabhu** [comment]
Could you please more elaborate? or give any usecae.

**Comment by EmanueleVolpato** [comment]
when I insert an event, with it I add the title, position, notes the start time, the end time and if it's all day or not, but the "URL" field is missing, which on ios is available on the app native calendar

**Comment by EmanueleVolpato** [comment]
And also the attendee in android

**Comment by EmanueleVolpato** [comment]
any updates?

**Comment by lakshmanaprabhu** [comment]
Update the plugin with URL-related implementations and will add attendee in events soon. 
Thanks for the suggestion @EmanueleVolpato

**Comment by EmanueleVolpato** [comment]
thanks @lakshmanaprabhu

**Comment by EmanueleVolpato** [comment]
any updates about attendee? thanks
@lakshmanaprabhu

**Comment by EmanueleVolpato** [comment]
ok thanks for add read-only attendee, work great, if possible also develop the add delete and modify participant would be perfect, this is missing to be the top library @lakshmanaprabhu

**Comment by EmanueleVolpato** [comment]
@lakshmanaprabhu with 1.0.9  version url does not work

**Comment by lakshmanaprabhu** [comment]
Added attendees edit support on version 2.0.0. Thanks @EmanueleVolpato.
